# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # The list of boards to build for, separated by spaces.
      board: nice_nano_v2
      # The list of shields to build for, separated by spaces.
      # The name of the shield should be the name of the DTS file in your boards/shields folder, without the .shield extension.
      # For example, for a Kyria, you would use "kyria_left kyria_right".
      # If you are building for a board that doesn't need a shield, you can leave this empty.
      shield: # Add your shield name here. For a 3x3 macropad, it might be the name of your .conf file if you made it a shield.
      # A list of extra arguments to pass to the build script, separated by spaces.
      # For example, to enable a custom shield named "my_shield", you would use "-- -DSHIELD=my_shield".
      # You can also use this to override settings in your config files.
      # For example, to change the idle timeout to 15 minutes, you would use "-- -DZMK_IDLE_TIMEOUT=900000".
      build-args:
